### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by sakkeerhussain** [albert-zhang/gen_xcassets#1]
While trying to check xc asset I am getting below error.

Traceback (most recent call last):
  File "check_xcassets.py", line 139, in <module>
    subprocess.check_call(['gen_xcassets.py', '-d', tmpCopiedDir, '-o', tmpOutputDir], stdout=fnull)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(_popenargs, *_kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(_popenargs, *_kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in **init**
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

May be this is because me added gen_xcassets.py to $PATH improperly.

**Comment by albert-zhang** [comment]
When you executing `check_xcassets.py`, please make sure `gen_xcassets.py` is in the current working directory, or else you have to add the directory of `gen_xcassets.py` to your $PATH to let the system know it.
